plugin: rest
resources:
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
     folio: 100       
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>0</STATUS>
        <TRACKID>1100</TRACKID>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1101
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>1</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1102
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>2</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1103
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>3</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1104
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>4</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1105
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>5</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1106
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>6</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1107
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>7</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1108
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>8</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1109
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>9</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1110
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>9</STATUS>
      </RECEPCIONDTE>
- method: POST
  path: /cgi_dte/UPL/DTEUpload
  formParams:
    folio: 1111
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    content: |
      <?xml version="1.0" ?>
      <RECEPCIONDTE>
        <RUTSENDER>${context.request.formParams.sender}</RUTSENDER>
        <RUTCOMPANY>${context.request.formParams.company}</RUTCOMPANY>
        <FILE>${context.request.formParams.filename}</FILE>
        <TIMESTAMP>${context.request.formParams.timestamp}</TIMESTAMP>
        <STATUS>9</STATUS>
      </RECEPCIONDTE>

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10000
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: DOK.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10100
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: DNK.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10200
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: FAU.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10300
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: FNA.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10400
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: FAN.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10500
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: EMP.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10600
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: TMD.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10700
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: TMC.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10800
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: MMD.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 10900
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: MMC.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 11000
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: AND.xml

- method: POST
  path: /DTEWS/QueryEstDte
  formParams:
      trackid: 12000
  response:
    template: true
    statusCode: 200
    headers:
      Content-Type: application/xml
    file: ANC.xml